name: Build Release APK

inputs:
  android-keystore-base64:
    required: true
  keystore-password:
    required: true
  android-key-alias:
    required: true
  android-key-alias-password:
    required: true
  build-type:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Install ImageMagick 7
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y libfuse2
        wget https://download.imagemagick.org/ImageMagick/download/binaries/magick
        chmod +x magick
        mv magick /usr/local/bin/

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Version Bump
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: composeApp/build.gradle.kts
        versionCode: ${{ github.run_number }}
        versionName: 1.0.${{ github.run_number }}

    - name: convert build type to lowercase
      id: convert
      run: |
        BUILD_TYPE_LOWER=$(echo "${{ inputs.build-type }}" | tr '[:upper:]' '[:lower:]')
        echo "build_type_lower=$BUILD_TYPE_LOWER" >> $GITHUB_OUTPUT
      shell: bash

    - name: Generate unsigned APK
      run: ./gradlew :composeApp:assemble${{ inputs.build-type }}Release --build-cache -x test -x lint
      shell: bash

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: composeApp/build/outputs/apk/${{ steps.convert.outputs.build_type_lower }}/release
        signingKeyBase64: ${{ inputs.android-keystore-base64 }}
        keyStorePassword: ${{ inputs.keystore-password }}
        alias: ${{ inputs.android-key-alias }}
        keyPassword: ${{ inputs.android-key-alias-password }}
      env:
        BUILD_TOOLS_VERSION: "35.0.0"

    - name: Set signed APK path to env
      run: |
        if [[ "${{ inputs.build-type }}" == "Production" ]]; then
          VERSION_NAME="Mena"
        else
          VERSION_NAME="Mena-${{ inputs.build-type }}"
        fi
        
        APK_NAME="${VERSION_NAME}-v1.0.${{ github.run_number }}.apk"
        
        mv composeApp/build/outputs/apk/${{ steps.convert.outputs.build_type_lower }}/release/composeApp-${{ steps.convert.outputs.build_type_lower }}-release-unsigned-signed.apk \
           composeApp/build/outputs/apk/${{ steps.convert.outputs.build_type_lower }}/release/$APK_NAME
        echo "APK_NAME=$APK_NAME" >> $GITHUB_OUTPUT
        echo "SIGNED_APK_PATH=composeApp/build/outputs/apk/${{ steps.convert.outputs.build_type_lower }}/release/$APK_NAME" >> $GITHUB_ENV
      shell: bash
