name: 'Send Slack Message'

inputs:
  slack-bot-token:
    required: true
  slack-notification-channel-id:
    required: true
  branch-name:
    required: true
  message:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y jq

    - name: Send Slack message
      shell: bash
      run: |
        messages=$(curl -s -X POST "https://slack.com/api/conversations.history" \
          -H "Authorization: Bearer ${{ inputs.slack-bot-token }}" \
          -H "Content-type: application/json" \
          --data "{\"channel\": \"${{ inputs.slack-notification-channel-id }}\"}")
        
        message_count=$(echo "$response" | jq '.messages | length')
        if [ -z "$message_count" ] || ! [[ "$message_count" =~ ^[0-9]+$ ]]; then
          message_count=0
        fi
    
        if [ "$message_count" -eq 0 ]; then
        echo "is_empty=true" >> "$GITHUB_OUTPUT"
        else
        echo "is_empty=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Send Slack messages (only if empty)
      if: steps.check_slack.outputs.is_empty == 'true'
      uses: ./.github/actions/create-slack-notification-template

    - name: Send Slack messages
      shell: bash
      run: |
        REGIONS=("WLT" "TRN" "FTH" "CHT" "DKN" "IDN")
        team=$(echo "${{ inputs.branch-name }}" | cut -d'/' -f2)
        prefix="${team:0:3}"

        for i in "${!REGIONS[@]}"; do
          if [[ "${REGIONS[$i]}" == "$prefix" ]]; then
            thread_ts=$(echo "$messages" | jq -r ".messages[$i].ts")

            curl -X POST "https://slack.com/api/chat.postMessage" \
              -H "Authorization: Bearer ${{ inputs.slack-bot-token }}" \
              -H "Content-type: application/json; charset=utf-8" \
              --data "{
                \"channel\": \"${{ inputs.slack-notification-channel-id }}\",
                \"thread_ts\": \"$thread_ts\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"${{ inputs.message }}\"
                    }
                  }
                ]
              }"
          fi
        done
