name: 'Send Slack Message'

inputs:
  slack-bot-token:
    required: true
  slack-notification-channel-id:
    required: true
  branch-name:
    required: true
  message:
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y jq

    - name: Send Slack message
      shell: bash
      run: |
        messages=$(curl -s -X POST "https://slack.com/api/conversations.history" \
          -H "Authorization: Bearer ${{ inputs.slack-bot-token }}" \
          -H "Content-type: application/json" \
          --data "{\"channel\": \"${{ inputs.slack-notification-channel-id }}\"}")
        echo "$messages"
        message_count=$(echo "$response" | jq '.messages | length')
        echo "$message_count"
        if [ -z "$message_count" ] || ! [[ "$message_count" =~ ^[0-9]+$ ]]; then
          message_count=0
        fi

    - name: Send Slack messages (only if empty)
      if: steps.count.outputs.message_count == '0'
      uses: ./.github/actions/send-default-slack-template
      with:
        slack-bot-token: ${{ inputs.slack-bot-token }}
        slack-notification-channel-id: ${{ inputs.slack-notification-channel-id }}

    - name: Send Slack messages
      shell: bash
      env:
        messages: steps.count.outputs.messages
      run: |
        echo "$messages"
        REGIONS=("WLT" "TRN" "FTH" "CHT" "DKN" "IDN")
        team=$(echo "${{ inputs.branch-name }}" | cut -d'/' -f2)
        prefix="${team:0:3}"
        echo "${REGIONS[$i]} = $prefix"
        for i in "${!REGIONS[@]}"; do
          if [[ "${REGIONS[$i]}" == "$prefix" ]]; then
            thread_ts=$(echo "$messages" | jq -r ".messages[$i].ts")
            echo "$thread_ts"
            curl -X POST "https://slack.com/api/chat.postMessage" \
              -H "Authorization: Bearer ${{ inputs.slack-bot-token }}" \
              -H "Content-type: application/json; charset=utf-8" \
              --data "{
                \"channel\": \"${{ inputs.slack-notification-channel-id }}\",
                \"thread_ts\": \"$thread_ts\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"${{ inputs.message }}\"
                    }
                  }
                ]
              }"
          fi
        done
