github_checks: false

flags:
  - core_chat_api
  - core_chat_data
  - core_chat_domain
  - core_chat_presentation
  - dukan_api
  - dukan_data
  - dukan_domain
  - dukan_presentation
  - faith_api
  - faith_data
  - faith_domain
  - faith_presentation
  - identity_api
  - identity_data
  - identity_domain
  - identity_presentation
  - trends_api
  - trends_data
  - trends_domain
  - trends_presentation
  - wallet_api
  - wallet_data
  - wallet_domain
  - wallet_presentation