name: "Send Region PRs to Slack"

inputs:
  slack-bot-token:
    required: true
  slack-notification-channel-id:
    required: true
  bot-app-id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack notifications
      shell: bash
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_NOTIFICATION_CHANNEL_ID: ${{ inputs.slack-notification-channel-id }}
        BOT_APP_ID: ${{ inputs.bot-app-id }}
      run: |
        REGIONS=("IDN" "DKN" "CHT" "FTH" "TRN" "WLT")

        for REGION in "${REGIONS[@]}"; do
          MESSAGE="${REGION} prs info"
          echo "Sending Slack notification for $REGION..."

          curl -X POST https://slack.com/api/chat.postMessage \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-type: application/json; charset=utf-8" \
            --data "{
              \"channel\": \"$SLACK_NOTIFICATION_CHANNEL_ID\",
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"$MESSAGE\"
                  }
                }
              ]
            }"
        done
              
        messages=$(curl -s -X POST "https://slack.com/api/conversations.history" \
        -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
        -H "Content-type: application/json" \
        --data "{\"channel\": \"$SLACK_NOTIFICATION_CHANNEL_ID\"}")
          
          bot_messages=$(echo "$messages" | jq --arg app_id "$BOT_APP_ID" '.messages[] | select(.app_id == $app_id)')
          echo "bot_messages :$bot_messages"
          echo "bot_messages=$(echo "$bot_messages" | jq -c -s .)" >> "$GITHUB_ENV"
