name: Deploy release APK from develop to Firebase

on:
  push:
    branches:
      - develop

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Sign APK
        uses: ./.github/actions/build_release.yml
        with:
          android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          android-key-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          android-key-alias-password: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

      - name: Deploy to Firebase
        uses: ./.github/actions/deploy_release_to_firebase.yml
        with:
          firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
          credential-file-content: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          signed-apk-path: ${{ env.SIGNED_APK_PATH }}