name: Notify Slack on PR Open

on:
  pull_request:
    types: [opened, reopened]

jobs:
  get-send-pr-open:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get last commit message
        id: commit
        run: |
          echo "message<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Notify Slack on PR Open
        uses: ./.github/actions/slack/send-pr-notification
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-notification-channel-id: ${{ secrets.SLACK_NOTIFICATION_CHANNEL_ID }}
          bot-app-id: ${{ secrets.BOT_APP_ID }}
          branch-name: ${{ github.head_ref }}
          message: |
            🚨 *New PR Open*
            PR opened by: ${{ github.event.pull_request.user.login }}
            Branch Name: ${{ github.head_ref }}
            PR: ${{ github.event.pull_request.html_url }}
