name: Send Slack Messages

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  slack-loop:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Send messages to Slack
        run: |
          #!/bin/bash
      
            messages=$(curl -s -X POST "https://slack.com/api/conversations.history" \
          -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -H "Content-type: application/json" \
          --data "{\"channel\": \"$SLACK_CHANNEL_ID\"}")

          REGIONS=("IDN" "DKN" "CHT" "FTH" "TRN" "WLT")
          echo "${messages}"
          team=$(echo "$BRANCH_NAME" | cut -d'\' -f2)
          prefix="${team:0:3}"

          for i in "${!REGIONS[@]}"; do
            if [[ "${REGIONS[$i]}" == "$prefix" ]]; then
              thread_ts=${$messages[$i].ts}
          
              curl -X POST "https://slack.com/api/chat.postMessage" \
                -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                -H "Content-type: application/json; charset=utf-8" \
                --data "{
                  \"channel\": \"$SLACK_CHANNEL_ID\",
                  \"thread_ts\": \"$thread_ts\",
                  \"blocks\": [
                    {
                      \"type\": \"section\",
                      \"text\": {
                        \"type\": \"mrkdwn\",
                        \"text\": \"hi\"
                      }
                    }
                  ]
                }"
            fi
          done
          
