name: Test Coverage and Codecov Report

on:
  workflow_run:
    workflows: ["Detect Changed Modules"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: []

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: detect-results

      - name: Load detect results
        id: vars
        run: |
          while IFS== read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done < detect_env.txt
          echo "matrix=$(echo $modules)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.vars.outputs.matrix }}

  test-modules:
    needs: test
    if: env.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.test.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew :${{ matrix.module }}:koverVerify --build-cache
      - run: ./gradlew :${{ matrix.module }}:koverXmlReport :${{ matrix.module }}:koverHtmlReport

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-coverage-report-${{ matrix.module }}
          path: ${{ matrix.module }}/build/reports/kover/html/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: xml-coverage-report-${{ matrix.module }}
          path: ${{ matrix.module }}/build/reports/kover/report.xml

  codecov:
    needs: [ test-modules ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: "xml-coverage-report-*"
          path: coverage-reports
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage-reports/
          fail_ci_if_error: true